let cidades_brasileiras = [
    "Aparecida de Goiânia",
    "Ananindeua",
    "Aracaju",
    "Belém",
    "Belford Roxo",
    "Belo Horizonte",
    "Brasília",
    "Cassapava",
    "Campinas",
    "Campo Grande",
    "Contagem",
    "Cuiabá",
    "Curitiba",
    "Feira de Santana",
    "Florianópolis",
    "Fortaleza",
    "Goiânia",
    "Guarulhos",
    "Jaboatão dos Guararapes",
    "João Pessoa",
    "Joinville",
    "Juiz de Fora",
    "Londrina",
    "Maceió",
    "Manaus",
    "Montes Claros",
    "Natal",
    "Niterói",
    "Nova Iguaçu",
    "Osasco",
    "Porto Alegre",
    "Recife",
    "Ribeirão das Neves",
    "Ribeirão Preto",
    "Rio de Janeiro",
    "Salvador",
    "Santa Maria",
    "Santo André",
    "Santos",
    "São Bernardo do Campo",
    "São Gonçalo",
    "São João de Meriti",
    "São José do Rio Preto",
    "São José dos Campos",
    "São Luís",
    "Serra",
    "Sorocaba",
    "Teresina",
    "Uberlândia",
    "Vila Velha",
    "Vitória",
    "Poços de Caldas"
  ]
 
  let position = cidades_brasileiras.indexOf('Cassapava')
  if(cidades_brasileiras[position] == "Cassapava"){
    cidades_brasileiras[position] = "Caçapava"
  }
  
  console.log(cidades_brasileiras);